### ISSUE TITLE
name ' ' is not defined

### ISSUE THREAD

**Issue by Ella77** [lovit/KR-WordRank#1]
scan vocabs ... 
num vocabs = 137500
done
Traceback (most recent call last):
  File "", line 18, in <module>
    ㅌ
NameError: name 'ᄐ' is not defined

**Comment by lovit** [comment]
This issue is closed? I guess that the issue is normalization of input text, is it right? Your comments help me make more complete algorithm. Please let me know if you have any discomfort.

**Comment by Ella77** [comment]
It just my little mistake ..Thanks:)
