### ISSUE TITLE
decaying factor를 단어별로 다르게 (bias) 할당

### ISSUE THREAD

**Issue by CHOOSLA** [lovit/KR-WordRank#13]
tutorials/krwordrank_word_and_keyword_extraction 에서
In [5] 파트 부분에
decaying factor를 단어별로 다르게 (bias) 할당할 수 있다고 적어주셨는데,
어떻게 다르게 할당하나요?

**Comment by ming99999** [comment]
krwordrank/word/_word.py 에서 extract 함수를 보시면
```
def extract(self, docs, beta=0.85, max_iter=10, num_keywords=-1,
        num_rset=-1, vocabulary=None, bias=None, rset=None):

        bias : None or dict
            User specified HITS bias term
```

따라서 {<단어> : <decaying factor 값>} 의 dictionary를 bias에 추가해주시면 될 것 같습니다.

**Comment by CHOOSLA** [comment]
bias의 값은
HITS 알고리즘에 있는 bias의 값인 것과 같이 계산하는 형태인가요?
여기에 있는 코드로하면
1 - beta / ( 그래프 노드의 총 개수 ) 로 계산이 되나요?

**Comment by CHOOSLA** [comment]
빠른 답변 정말 감사합니다!
그럼 summarize_with_sentences 에서도 extract 함수를 쓰는데, 여기로 bias를 넘겨서 사용할 수 있겠죠...?

그리고 bias는
krwordrank/word/_rank.py 에서

<pre>
<code>
def _update(rank, graph, bias, dw, beta):
    rank_new = {}
    for to_node, from_dict in graph.items():
        rank_new[to_node] = sum([w * rank[from_node] for from_node, w in from_dict.items()])
        rank_new[to_node] = beta * rank_new[to_node] + (1 - beta) * bias.get(to_node, dw)
    return rank_new
</code>
</pre>
에서 
<pre>
<code>
rank_new[to_node] = sum([w * rank[from_node] for from_node, w in from_dict.items()])
</code>
</pre>

는 현재 노드의 LBV 값을 왼쪽에 등장한 단어 후보의 RBV의 합을 구하는 과정이고

<pre>
<code>
rank_new[to_node] = beta * rank_new[to_node] + (1 - beta) * bias.get(to_node, dw)
</code>
</pre>

는 현재의 노드에 새로운 값을 갱신하는 데에 지수이동평균을 사용하신 것이 맞나요?
그렇다면 beta에 들어간 기본값이 0.85를 생각해보았을 때, 0,15 * ( 원하는 bias ) 로 계산되는 것이 맞습니까?

질문이 길어져서 죄송합니다.. 아직 공부하는 중이라 모르는 게 많네요

**Comment by ming99999** [comment]
summarize_with_sentences 에서 bias를 사용하기 위해서 이 함수 내의 KRWordRank로 bias를 넘길 수 있도록 수정해서 사용해야 할 것 같습니다.

rank의 _update 부분은 pagerank를 생각하시고 보시면 편할것같습니다. 
업데이트되는 rank는 현재 graph를 기준으로 'to_node'와 연결된 node들의 rank를 합한 뒤
beta만큼의 비율(여기서는 0.85)만 취하고 나머지 1-beta(0.15)의 비율로 자기 자신을 선택했을 때의 중요도를 취합니다.
'to_node'에 해당하는 단어에 bias 값이 있다면 해당 bias 값만큼 비중을 주고, 
없는 경우에는 dw만큼(sum_weight / number_of_nodes)의 비중을 주는 것이죠.

lovit님의 블로그에 관련 식에 대한 자세한 설명이 있으니 참고해보시면 좋을 것 같습니다.
https://lovit.github.io/machine%20learning/2018/04/16/pagerank_and_hits/

**Comment by CHOOSLA** [comment]
감사합니다 해결했습니다!

**Comment by CHOOSLA** [comment]
_sentence.py 에서 summarize_with_sentences 함수에서
<pre>
<code>
def summarize_with_sentences(texts, num_keywords=100, num_keysents=10, diversity=0.3, stopwords=None, scaling=None,
    penalty=None, min_count=5, max_length=10, beta=0.85, max_iter=10, num_rset=-1, verbose=False, bias=None)
</code>
</pre>
이렇게 bias 매개변수를 추가하고, 

<pre>
<code>
    # 기존코드의 매개변수에서 bias만 추가로 넘겨줌
    keywords, rank, graph = wordrank_extractor.extract(texts,
        beta, max_iter, num_keywords=num_keywords_, num_rset=num_rset,bias=bias)
</code>
</pre>
매개변수의 bias를 summarize_with_sentences 함수내부의 wordrank_extractor.extract에도 bias를 넘겨줬습니다.

결국 bias가 _rank.py에 있는 _update까지 넘어가긴 하는데, 
extract 함수에  {<단어> : <decaying factor 값>} 의 dictionary를 bias에 추가하면 또 문제가 있습니다.

결국 PageRank를 통해서 계산하는 것은 _rank.py에서 _update 함수를 통해 계산이 되는데, 여기서 계산에 쓰이는 dictionary의 key 값은 <단어>가 아닌 encoding 된 <단어>를 사용하여 계산해서 문제가 생기던 것이었습니다.
이문제는, _word.py 에서 train함수에서 scan_vocab함수를 통해 문장을 L,R로 분리하고 빈도수가 높은 수만큼 내림차순한 것을 self.vocabulary에 저장하고 self.vocabulary를 다시 train함수에 있는 _construct_word_graph함수안에서 _encode_token 함수를 통해 <단어>를 encode 하는 것을 발견했습니다.

그래서 _word.py에서
<pre>
<code>
    # 기존코드의 매개변수에서 bias만 추가로 넘겨줌
   rank, graph = self.train(docs, beta, max_iter, vocabulary, bias))
</code>
</pre>

<pre>
<code>
    # 기존코드의 매개변수만 추가
       def train(self, docs, beta=0.85, max_iter=10, vocabulary=None, bias_list=None)
</code>
</pre>
train 함수에 bias를 넘기게 했고,

train 함수에서
<pre>
<code>
        encoded_bias = {}
        # 받은 bias를 encode 시키기 위한 작업
        if bias_list:
            for word, rank in bias_list.items():
                encoded_word = self.token2int((word, 'L'))
                if encoded_word != -1:
                    encoded_bias[encoded_word] = rank

        rank = hits(graph, beta, max_iter, encoded_bias,
                    sum_weight=self.sum_weight,
                    number_of_nodes=len(self.vocabulary),
                    verbose=self.verbose
                    )
</code>
</pre>
기존에 있던 self.token2int 함수를 사용해서 encode 되었던 단어들에서 제가 추가한 bias의 단어와 일치하는 것들만 encode 된 단어들로 바꿔서 hits함수에 넘겨주었습니다.

결국 제가 원하는 데로 결과가 출력되 었고 해결했습니다! 감사드립니다!

**Comment by lovit** [comment]
@ming99999 
상세한 설명 감사합니다. 다른 일들 때문에 대응 못하고 있었는데 자세하고 정확한 답변을 대신해 주셨군요 ㅠㅜ 감동!!

**Comment by lovit** [comment]
@CHOOSLA 
직접 해결법도 제시해 주셔서 감사합니다. `summarize_with_keywords`, `summarize_with_sentences` 함수에 `bias` 를 입력하는 부분을 만들어두지 않았었군요. 해결법도 모두 옳다고 생각됩니다. 해당 내용을 PR 로 수정/기여 해 주신다면 저도 정말 감사할 것 같습니다.

이렇게 수정 코드까지 남겨주셨으니, 의견 하나 드리자면 위에서 기술해 주신 코드의 (아래 다시 기술) `bias_list` 는 실제로는 `dict` 형식이니 아래처럼 이름을, 그리고 HITS 나 PageRank 에서 사용하는 rank 개념과 bias value 개념을 구분하기 위해 `rank -> value` 로 바꿔 기술하면 더 명료한 코드일 것 같습니다.

(위에서 기술해 주신 수정 코드)
```python
        encoded_bias = {}
        # 받은 bias를 encode 시키기 위한 작업
        if bias_list:
            for word, rank in bias_list.items():
                encoded_word = self.token2int((word, 'L'))
                if encoded_word != -1:
                    encoded_bias[encoded_word] = rank

        rank = hits(graph, beta, max_iter, encoded_bias,
                    sum_weight=self.sum_weight,
                    number_of_nodes=len(self.vocabulary),
                    verbose=self.verbose
                    )
```

(제안하는 renamed variables)
```python
        encoded_bias = {}
        # 받은 bias를 encode 시키기 위한 작업
        if custom_bias_dict:
            for word, value in custom_bias_dict.items():
                encoded_word = self.token2int((word, 'L'))
                if encoded_word != -1:
                    encoded_bias[encoded_word] = value

        rank = hits(graph, beta, max_iter, encoded_bias,
                    sum_weight=self.sum_weight,
                    number_of_nodes=len(self.vocabulary),
                    verbose=self.verbose
                    )
```

적극적인 질문과 코드 수정 의견, 다시 한 번 감사합니다.

**Comment by CHOOSLA** [comment]
저야 말로 감사합니다! 학생 신분에서 좋은 경험이었던 것 같습니다! 일단 지금은 시간이 없어서 다음주 평일 중에 요청하겠습니다!

**Comment by lovit** [comment]
#14 의 내용 확인했으며, master 에 머징하였습니다. 감사합니다.

**Comment by CHOOSLA** [comment]
넵 수고하세요~!
