### ISSUE TITLE
pip install krwordrank 시 에러가 뜹니다

### ISSUE THREAD

**Issue by aerialcombat** [lovit/KR-WordRank#2]
파이썬은 처음이라 실행까지 어려움이 많습니다.

권하신 pip install krwordrank를 mac과 ubuntu에서 실행해 보았으나

```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v7DDo8/krwordrank/setup.py", line 1, in <module>
        from description import __version__, __author__
    ImportError: No module named description
```

아래 에러를 뱉어내네요. 감사합니다.

**Comment by lovit** [comment]
아마 Python 2.x 를 이용하시는 거라 생각됩니다. 저는 Python 3.5 이상에서만 테스트를 해봤습니다. 3.x 환경으로 이용해주세요. Python version 은 README 에 언급하도록 하겠습니다.

**Comment by aerialcombat** [comment]
아! 이렇게도 빨리... 방금 그 부분을 읽고 막 3.x로 해보려던 참이었습니다. 감사합니다.

**Comment by lovit** [comment]
마침 컴퓨터 앞에 앉아있었습니다. 설치해보시고 안되시면 커멘트 남겨주세요. 감사합니다.

**Comment by aerialcombat** [comment]
블로그 읽으면서 많이 배우고 있습니다. 아직 겉핥기만 하는 수준이지만, 하고 있는 프로젝트에 필요한 기능이라서 많은 도움이 되고 있습니다. 감사합니다.

**Comment by aerialcombat** [comment]
```
$ python3 main.py
      입니:	1.1845
      문장:	0.8770
```
테스트 런 까지는 성공했습니다 ㅎㅎ

이제는 파이썬을 더욱 배워서 여기서 빌드업을 할지, 아니면 제가 익숙한 언어로 포팅을 해야할지 고민을 할 차례인 것 같습니다. 

감사합니다.

**Comment by lovit** [comment]
좋은 결과 얻길 바랍니다. 나중에 작업 마무리 되시면 연락주세요~ 구경갈게요~

**Comment by aerialcombat** [comment]
제가 현재 만들려고 하는 것은 해시태그 추천 모듈입니다.

제가 제작중인 커뮤니티 사이트에 사용자가 글을 쓸때, 그 본문에 알맞은 해시태그를 추천해 주는 것이지요.

현재 golang으로 서버를 제작 중인데, 해시태그 추천 모듈은 별도의 서버로 돌릴 예정입니다.

추천 방식은 본문에서 키워드를 추출해서 이미 알려져 있는 해시태그 리스트와 크로스체킹 한 뒤, 해당 키워드를 해시태그로 추천하는 방식이 될 것 같습니다.

제가 만들고 있는 프로젝트가 오픈이 되면 연락드리겠습니다. 감사합니다. ^^
