### ISSUE TITLE
simple example 

### ISSUE THREAD

**Issue by Ella77** [lovit/KR-WordRank#3]
Thanks for great project ...! I'm using this kr-wordrank for data analytics  ( especially for my application's user) 

I was using for big data log succesfully... But When I ran my simple code again, somewhat weird result comes out. Maybe it can be my mistake doing something with original code. 
`
from PIL import Image
from krwordrank.word import KRWordRank
from krwordrank.hangle import normalize
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import numpy as np

font_path = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
min_count = 1  # 단어의 최소 출현 빈도수 (그래프 생성 시)
max_length = 10 # 단어의 최대 길이
wordrank_extractor = KRWordRank(min_count, max_length)
beta = 0.85    # PageRank의 decaying factor beta
max_iter = 10

texts = ['양','양','양고기','치킨',
'치킨',
'떡볶이',
'떡볶이',
'오뎅',
'오뎅',
'오뎅',
'떡볶이',
'떡볶이',
'오뎅',
'오뎅'
,'오뎅' ]
keywords, rank, graph = wordrank_extractor.extract(texts, beta, max_iter)

font_path = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
wordcloud = WordCloud(font_path = font_path,
    width = 700,
    height = 800,
    background_color = "white",
                      )
for word, r in sorted(keywords.items(), key=lambda x:x[1], reverse=True)[:30]:
        print('%8s:\t%.4f' % (word, r))
`

The result was 
양고:	1.0000
떡볶:	1.0000 

And Here is vocabulary dict {('오뎅', 'L'): 0, ('오', 'L'): 1, ('뎅', 'R'): 2, ('떡볶이', 'L'): 3, ('떡', 'L'): 4, ('볶이', 'R'): 5, ('떡볶', 'L'): 6, ('이', 'R'): 7, ('양', 'L'): 8, ('치킨', 'L'): 9, ('치', 'L'): 10, ('킨', 'R'): 11, ('양고기', 'L'): 12, ('고기', 'R'): 13, ('양고', 'L'): 14, ('기', 'R'): 15}

===================
When I add verbose = True option and insert wordrank_extractor.extract(texts, beta, max_iter,verbose) 

Traceback (most recent call last):
  File "virtualenvs/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2869, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-cc9484fc983b>", line 1, in <module>
    runfile(PycharmProjects/Count_chat_log/sample.py', wdir='PycharmProjects/Count_chat_log')
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "PycharmProjects/Count_chat_log/sample.py", line 29, in <module>
    keywords, rank, graph = wordrank_extractor.extract(texts, beta, max_iter,verbose)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/krwordrank/word/_word.py", line 58, in extract
    rank, graph = self.train(docs, beta, max_iter, vocabulary, bias)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/krwordrank/word/_word.py", line 144, in train
    verbose=self.verbose
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/krwordrank/graph/_rank.py", line 9, in hits
    dw = sum_weight / number_of_nodes
ZeroDivisionError: division by zero

**Comment by lovit** [comment]
Thank you for using this library first.

There are two problems with this issue. First, the version of the library you are using is not up-to-date. In the latest version (0.1.3), the extract function does not have a verbose argument. Instead, set the verbose in the init function.

```python
krwordrank = KRWordRank (verbose = True)
```

Second, I assumed the input format as a list of sentences. Each word in the sentence is separated by a white space. KR-WordRank performs word extraction and keyword extraction at the same time. To do this, KR-WordRank uses a Korean word structure that combines words (especially noun) and suffixes (josa). It is very difficult to extract the words from list of word. The purpose of this library is to extract keywords without setting up the tokenizer in situations where the tokenizer is not working well due to an out of vocabulary problem. Therefore, retry with the sentences combined with various suffixes by inputting specific words.

```python
texts = [
  '난 치킨을 좋아해요',
  '치킨이랑 떡볶이랑 맛있지',
  '야식으로 치킨어때',
  '치킨이 진리지',
  '치킨과 떡볶이',
  '치킨이랑 떡볶이로 예문 만드니까 배고프네',
  '치킨에는 맥주지',
  '떡볶이에는 튀김',
  '치킨 맥주를 합쳐 치맥'
]

from krwordrank.word import KRWordRank

min_count = 1 # 단어의 최소 출현 빈도수 (그래프 생성 시)
max_length = 10 # 단어의 최대 길이
wordrank_extractor = KRWordRank(min_count, max_length, verbose=True)
beta = 0.85 # PageRank의 decaying factor beta
max_iter = 10

keywords, rank, graph = wordrank_extractor.extract(texts, beta, max_iter)
```

      치킨:	3.8894
     떡볶이:	2.2671
      튀김:	1.8797
      예문:	1.7708
    배고프네:	1.6414
    야식으로:	1.6070
     맥주지:	1.4638
    만드니까:	1.3972
     맛있지:	1.3880
     진리지:	1.0050
      합쳐:	0.9044
      좋아:	0.8087
      치맥:	0.7119

**Comment by Ella77** [comment]
Thanks a lot !!
